### ISSUE TITLE
Translation Help

### ISSUE THREAD

**Issue by TheRojam** [tenman/raindrops#3]
For what is "About Base Color related Class" needed? in which case is this used?

**Comment by tenman** [comment]
Base Color is
Dashboard / Appearance / Customize / Presentation / Color Scheme / Base Color

When changing the color, the color of the sample of the Help tab will also be changed at the same time

After please use the CSS class, such as color-2 in the post body

When you use this class, you can dynamically change the color scheme if you change the base color.
